services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - wpnet

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: mitienda.local
      VIRTUAL_PORT: 80
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: forge
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wpnet
    expose:
      - "80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: server-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: forge
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

volumes:
  wordpress_data:
  db_data:

networks:
  wpnet:
    driver: bridge

