# services:
#   nginx-proxy:
#     image: nginxproxy/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       - "80:80"
#       - "443:443"
#     environment:
#       ENABLE_IPV6: "false"
#     volumes:
#       - ./certs:/etc/nginx/certs:ro
#       - /etc/nginx/vhost.d
#       - /usr/share/nginx/html
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#     networks:
#       - wpnet

#   letsencrypt:
#     image: nginxproxy/acme-companion
#     container_name: nginx-letsencrypt
#     environment:
#       DEFAULT_EMAIL: tu-email@dominio.com
#     volumes_from:
#       - nginx-proxy
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./certs:/etc/nginx/certs:rw
#       - ./acme:/etc/acme.sh
#     networks:
#       - wpnet

#   wordpress:
#     image: wordpress:latest
#     container_name: wordpress
#     environment:
#       VIRTUAL_HOST: mitienda.local
#       VIRTUAL_PORT: 80
#       LETSENCRYPT_HOST: mitienda.local
#       LETSENCRYPT_EMAIL: tu-email@dominio.com
#       WORDPRESS_DB_HOST: db
#       WORDPRESS_DB_NAME: wordpress
#       WORDPRESS_DB_USER: forge
#       WORDPRESS_DB_PASSWORD: secret
#     volumes:
#       - wordpress_data:/var/www/html
#     networks:
#       - wpnet
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7
#     container_name: server-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: forge
#       MYSQL_PASSWORD: secret
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - wpnet

# volumes:
#   wordpress_data:
#   db_data:

# networks:
#   wpnet:
#     driver: bridge
